export const ResponseData = (result) => {
  const {
    quoteType,
    exchange,
    shortName,
    longName,
    market,
    currency,
    regularMarketChangePercent,
    regularMarketPrice,
    regularMarketChange,
    regularMarketDayRange,
    regularMarketVolume,
    fullExchangeName,
    regularMarketOpen,
    averageDailyVolume3Month,
    fiftyTwoWeekRange,
    trailingPE,
    epsTrailingTwelveMonths,
    marketCap,
    symbol,
  } = result;

  return {
    quoteType,
    exchange,
    shortName,
    longName,
    market,
    currency,
    regularMarketChangePercent,
    regularMarketPrice,
    regularMarketChange,
    regularMarketDayRange,
    regularMarketVolume,
    fullExchangeName,
    regularMarketOpen,
    averageDailyVolume3Month,
    fiftyTwoWeekRange,
    trailingPE,
    epsTrailingTwelveMonths,
    marketCap,
    symbol,
  };
};
